### PR TITLE
Fixed bugs where non-existant global verbose was used instead of Cnt[…

### PR DESCRIPTION
**Pull request by davecash75**
…'VERBOSE']

### CODE REVIEW

**Comment by pjmark** [comment]
Not sure what happened, but the verbose=True is defined as on optional argument in line 439. So it should not be problematic.  Can you see if you have/had the verbose flag defined?

**Comment by davecash75** [comment]
Hi Pawel-
That appears to be true for the function align_mumap, but not for the function pct_mumap, which starts on 771 and does not have a verbose variable passed through the function parameters. Would you prefer the fix to be verbose=True there and then passing that verbose on to subsequent functions?

**Comment by pjmark** [comment]
Yes please!  Thanks Dave.

**Comment by davecash75** [comment]
Hi Pawel-
That's sorted. See if it looks good to you now.

**Comment by pjmark** [comment]
Thank you, Dave!

**Pull request merged**
